import nbformat as nbf
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read_nb(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return nbf.read(f, as_version=4)


def write_nb(path: Path, nb):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        nbf.write(nb, f)


def md(text: str):
    return nbf.v4.new_markdown_cell(text)


def code(text: str):
    return nbf.v4.new_code_cell(text)


def build_prac04():
    path = ROOT / "Prac_04" / "homework" / "Homework.ipynb"
    nb = read_nb(path)
    updates = {
        4: """# Convert image to gray scale\ngray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)\ngray""",
        5: """# Obtain edge map\n# Hint: you can use Canny edge detector with th_low = 100, th_high = 150\nedges = cv2.Canny(gray, threshold1=100, threshold2=150)\n\n# We are only interseted in the road so we will remove everything above the horizon\nedges[0:350] = 0\nedges""",
        7: """# Apply Hough transform to parametrize the lines\n# Hint 1: Offset resolution of 2 pixels and slope resolution of 2 degrees work well in this case\n# Hint 2: A suitable value for the accumulator threshold is 190\nlines = cv2.HoughLines(edges, rho=2, theta=np.deg2rad(2), threshold=190)\n# Let's get rid of the unnecessary dimension\nlines = lines[:, 0, :]\nlines.shape""",
        8: """# Plot the resulting Hough lines\nresult = np.copy(img)\n        \nfor line in lines:\n    rho = line[0]\n    theta = line[1]\n    \n    a = math.cos(theta)\n    b = math.sin(theta)\n    \n    x0 = a * rho\n    y0 = b * rho\n    \n    pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))\n    pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))\n    \n    cv2.line(result, pt1, pt2, (255, 0, 0), 1, cv2.LINE_AA)\n\nplt.subplot(121), plt.imshow(edges, cmap='gray'), plt.title('Edge map')\nplt.subplot(122), plt.imshow(result), plt.title('Hough lines')\nplt.show()""",
        10: """# Filter out all lines that are approximately horizontal (+/- 20 degrees). \nfiltered_lines = []\nfor line in lines:\n    # Extract theta for current line (remember Hough works with radians)\n    theta = line[1]\n    # Keep line if theta is not horizontal\n    if abs(np.rad2deg(theta) - 90) > 20:\n        filtered_lines.append(line)\n\nfiltered_lines = np.array(filtered_lines)\nfiltered_lines.shape""",
        11: """# Let's plot the resulting filtered lines\nresult = np.copy(img)\n \nfor line in filtered_lines:\n    rho = line[0]\n    theta = line[1]\n    \n    a = math.cos(theta)\n    b = math.sin(theta)\n    x0 = a * rho\n    y0 = b * rho\n    \n    pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))\n    pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))\n    cv2.line(result, pt1, pt2, (0, 255, 0), 1, cv2.LINE_AA)\n\nplt.subplot(121), plt.imshow(edges, cmap='gray'), plt.title('Edge map')\nplt.subplot(122), plt.imshow(result), plt.title('Filtered Hough lines')\nplt.show()""",
        14: """# Again, let's plot the resulting filtered lines\nresult = np.copy(img)\n    \nfor line in kmeans.cluster_centers_:\n    rho = line[0]\n    theta = line[1]\n    \n    a = math.cos(theta)\n    b = math.sin(theta)\n    x0 = a * rho\n    y0 = b * rho\n    \n    pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))\n    pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))\n    cv2.line(result, pt1, pt2, (255, 255, 0), 2, cv2.LINE_AA)\n\nplt.subplot(121), plt.imshow(edges, cmap='gray'), plt.title('Edge map')\nplt.subplot(122), plt.imshow(result), plt.title('Clustered lane candidates')\nplt.show()""",
    }
    for idx, src in updates.items():
        nb.cells[idx].source = src
    nb.cells[15].source = """### Questions\n* Do you see anything strange in the final result?\n\nThe detector still returns multiple lines for the same physical lane marking and some of them extend across the whole image. This happens because the classical Hough transform parametrizes infinite lines rather than finite lane segments.\n\n* Do you think the Hough transform resolution is important for obtaining a good result? Why?\n\nYes. If the `rho` or `theta` resolution is too coarse, nearby lane candidates collapse into the same bin and localization becomes inaccurate. If the resolution is too fine, the votes spread across many bins and the detector becomes noisy.\n\n* Do you think the Hough transform accumulator threshold is important for obtaining a good result? Why?\n\nYes. A low threshold keeps many weak responses and produces clutter. A high threshold suppresses noise but can also remove valid lane lines. The threshold controls the precision/recall trade-off of the detector."""  # noqa: E501
    write_nb(path, nb)


def build_prac05():
    path = ROOT / "Prac_05" / "homework" / "Homework.ipynb"
    nb = read_nb(path)
    updates = {
        3: """# Load image\nimg = cv2.imread('../data/kodim23.png')\n# Convert it to RGB\nimg = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n# Plot it\nplt.imshow(img)\nplt.show()""",
        7: """# Cast the image to float\nimg = img.astype(np.float32)\n\n# Prepare for quantization\nrows, cols, channels = img.shape\nquantized = np.zeros_like(img)\n\n# Apply quantization\nfor r in range(rows):\n    for c in range(cols):\n        # Extract the original pixel value\n        pixel = img[r, c, :]\n        \n        # Find the closest colour from the pallette (using absolute value/Euclidean distance)\n        distances = np.linalg.norm(colors - pixel, axis=1)\n        new_pixel = colors[np.argmin(distances)]\n        \n        # Apply quantization\n        quantized[r, c, :] = new_pixel""",
        8: """# Show quantized image (don't forget to cast back to uint8)\nquantized_uint8 = np.clip(quantized, 0, 255).astype(np.uint8)\nplt.imshow(quantized_uint8)\nplt.title('Optimally quantized image')\nplt.show()""",
        9: """# Compute average quantization error\navg_quant_error = np.mean(np.linalg.norm(img - quantized, axis=2))\nprint('Average quantization error:', avg_quant_error)""",
        11: """# Make a temporal copy of the original image, we will need it for error diffusion\nimg_tmp = np.copy(img)\ndithering = np.zeros_like(img)\n\nfor r in range(1, rows-1):\n    for c in range(1, cols-1):\n        # Extract the original pixel value\n        pixel = img_tmp[r, c, :]\n        # Find the closest colour from the pallette (using absolute value/Euclidean distance)\n        distances = np.linalg.norm(colors - pixel, axis=1)\n        new_pixel = colors[np.argmin(distances)]\n        \n        # Compute quantization error\n        quant_error = pixel - new_pixel\n        \n        # Diffuse the quantization error accroding to the FS diffusion matrix\n        img_tmp[r, c + 1, :] += quant_error * 7 / 16\n        img_tmp[r + 1, c - 1, :] += quant_error * 3 / 16\n        img_tmp[r + 1, c, :] += quant_error * 5 / 16\n        img_tmp[r + 1, c + 1, :] += quant_error * 1 / 16\n        \n        # Apply dithering\n        dithering[r, c, :] = new_pixel\n\ndithering = np.clip(dithering, 0, 255)""",
        12: """# Show quantized image (don't forget to cast back to uint8)\nplt.subplot(121), plt.imshow(quantized_uint8), plt.title('Optimally quantized')\nplt.subplot(122), plt.imshow(dithering.astype(np.uint8)), plt.title('Floyd-Steinberg dithering')\nplt.show()""",
        13: """# Compute average quantization error for dithered image\navg_dith_error = np.mean(np.linalg.norm(img - dithering, axis=2))\nprint('Average dithering error:', avg_dith_error)""",
        16: """from sklearn.cluster import KMeans\npixels = np.reshape(img, (-1, 3))\nkmeans = KMeans(n_clusters=16, n_init=10, random_state=42).fit(pixels)\ncolors = kmeans.cluster_centers_\ncolors""",
    }
    for idx, src in updates.items():
        nb.cells[idx].source = src
    nb.cells.insert(15, code("""# Repeat the same process with black and white only\nbw_colors = np.array([[0, 0, 0], [255, 255, 255]], dtype=np.float32)\n\nbw_quantized = np.zeros_like(img)\nbw_tmp = np.copy(img)\nbw_dithered = np.zeros_like(img)\n\nfor r in range(rows):\n    for c in range(cols):\n        pixel = img[r, c, :]\n        new_pixel = bw_colors[np.argmin(np.linalg.norm(bw_colors - pixel, axis=1))]\n        bw_quantized[r, c, :] = new_pixel\n\nfor r in range(1, rows - 1):\n    for c in range(1, cols - 1):\n        pixel = bw_tmp[r, c, :]\n        new_pixel = bw_colors[np.argmin(np.linalg.norm(bw_colors - pixel, axis=1))]\n        err = pixel - new_pixel\n        bw_tmp[r, c + 1, :] += err * 7 / 16\n        bw_tmp[r + 1, c - 1, :] += err * 3 / 16\n        bw_tmp[r + 1, c, :] += err * 5 / 16\n        bw_tmp[r + 1, c + 1, :] += err * 1 / 16\n        bw_dithered[r, c, :] = new_pixel\n\nplt.subplot(121), plt.imshow(bw_quantized.astype(np.uint8)), plt.title('B/W quantized')\nplt.subplot(122), plt.imshow(np.clip(bw_dithered, 0, 255).astype(np.uint8)), plt.title('B/W dithering')\nplt.show()"""))
    nb.cells.append(code("""# Bonus: repeat FS dithering using the optimal 16-color k-means palette\nkm_quantized = np.zeros_like(img)\nkm_tmp = np.copy(img)\nkm_dithered = np.zeros_like(img)\n\nfor r in range(rows):\n    for c in range(cols):\n        pixel = img[r, c, :]\n        new_pixel = colors[np.argmin(np.linalg.norm(colors - pixel, axis=1))]\n        km_quantized[r, c, :] = new_pixel\n\nfor r in range(1, rows - 1):\n    for c in range(1, cols - 1):\n        pixel = km_tmp[r, c, :]\n        new_pixel = colors[np.argmin(np.linalg.norm(colors - pixel, axis=1))]\n        err = pixel - new_pixel\n        km_tmp[r, c + 1, :] += err * 7 / 16\n        km_tmp[r + 1, c - 1, :] += err * 3 / 16\n        km_tmp[r + 1, c, :] += err * 5 / 16\n        km_tmp[r + 1, c + 1, :] += err * 1 / 16\n        km_dithered[r, c, :] = new_pixel\n\nplt.subplot(121), plt.imshow(np.clip(km_quantized, 0, 255).astype(np.uint8)), plt.title('16-color quantized')\nplt.subplot(122), plt.imshow(np.clip(km_dithered, 0, 255).astype(np.uint8)), plt.title('16-color FS dithering')\nplt.show()"""))
    nb.cells[14].source = """### Questions\n* Which image has higher quantization error? Optimally quantized or dithered?\n\nThe dithered image typically has a slightly higher average pixel-wise quantization error because it intentionally redistributes that error to neighboring pixels.\n\n* Which image looks better to you?\n\nThe dithered image looks better because the distributed error preserves local contrast and visual detail instead of forming large flat posterized regions.\n\n* Can you repeat the same process using only two colours: black and white? Show me :-)\n\nYes. The extra cell above repeats the process with a black-and-white palette and shows that dithering is especially useful when the palette is very small."""  # noqa: E501
    write_nb(path, nb)


def build_prac06():
    path = ROOT / "Prac_06" / "Prac 06.1" / "homework" / "Homework.ipynb"
    nb = nbf.v4.new_notebook()
    nb.cells = [
        md("# Prac 06.1\n\nThis environment does not provide `dlib` on Python 3.13, so the notebook uses OpenCV's Haar cascade as a fully executable fallback for face detection."),
        code("""import cv2\nfrom pathlib import Path\nfrom matplotlib import pyplot as plt\n\nplt.rcParams['figure.figsize'] = [15, 10]\nBASE = Path('..')\nCASCADE_PATH = Path(cv2.data.haarcascades) / 'haarcascade_frontalface_default.xml'\nface_detector = cv2.CascadeClassifier(str(CASCADE_PATH))\nprint('Cascade loaded:', not face_detector.empty())"""),
        md("### Step 1\n\nLoad an image that contains faces."),
        code("""img_bgr = cv2.imread(str(BASE / 'data' / 'eu_summit.jpg'))\nimg = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)\ngray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)\nplt.imshow(img)\nplt.title('Original image')\nplt.axis('off')\nplt.show()"""),
        md("### Step 2 and Step 3\n\nLoad the predictor and run it on the image."),
        code("""faces = face_detector.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))\nprint('Detected faces:', len(faces))\nfaces[:5] if len(faces) else faces"""),
        md("### Step 4\n\nDraw bounding boxes around the detected faces and plot the result."),
        code("""result = img.copy()\ncolors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0), (255, 0, 255), (0, 255, 255)]\nfor idx, (x, y, w, h) in enumerate(faces):\n    color = colors[idx % len(colors)]\n    cv2.rectangle(result, (x, y), (x + w, y + h), color, 3)\n    cv2.putText(result, f'Face {idx + 1}', (x, max(20, y - 8)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)\nplt.imshow(result)\nplt.title('Detected faces')\nplt.axis('off')\nplt.show()"""),
        md("### Step 5\n\nRepeat the process on a different image."),
        code("""img2_bgr = cv2.imread(str(BASE / 'data' / 'zelensky.jpg'))\nimg2 = cv2.cvtColor(img2_bgr, cv2.COLOR_BGR2RGB)\ngray2 = cv2.cvtColor(img2, cv2.COLOR_RGB2GRAY)\nfaces2 = face_detector.detectMultiScale(gray2, scaleFactor=1.1, minNeighbors=4, minSize=(25, 25))\nresult2 = img2.copy()\nfor idx, (x, y, w, h) in enumerate(faces2):\n    color = colors[idx % len(colors)]\n    cv2.rectangle(result2, (x, y), (x + w, y + h), color, 3)\nplt.imshow(result2)\nplt.title(f'Challenging image: {len(faces2)} face(s) detected')\nplt.axis('off')\nplt.show()"""),
        md("### Discussion\n\nThe detector works well for large frontal faces with good contrast. It becomes less reliable when the faces are small, rotated, or partially occluded, which is expected for a classical Haar-cascade approach."),
    ]
    write_nb(path, nb)


def build_prac07():
    path = ROOT / "Prac_07" / "Prac 07.2" / "homework" / "Homework.ipynb"
    nb = nbf.v4.new_notebook()
    nb.cells = [
        md("# Prac 07.2\n\nThis notebook inspects the extracted GTSRB training split: random samples, per-class histogram, and additional analysis of resolution and brightness."),
        code("""from pathlib import Path\nfrom collections import Counter\nimport cv2\nimport numpy as np\nimport pandas as pd\nfrom matplotlib import pyplot as plt\n\nplt.rcParams['figure.figsize'] = [15, 10]\nROOT = Path('..') / 'data' / 'GTSRB' / 'Training'\nprint('Dataset root:', ROOT.resolve())\nprint('Exists:', ROOT.exists())"""),
        code("""records = []\nfor class_dir in sorted(ROOT.glob('*')):\n    if not class_dir.is_dir():\n        continue\n    csv_path = class_dir / f'GT-{class_dir.name}.csv'\n    df = pd.read_csv(csv_path, sep=';')\n    df['ClassId'] = int(class_dir.name)\n    df['Path'] = df['Filename'].apply(lambda name: str(class_dir / name))\n    records.append(df[['Path', 'Width', 'Height', 'ClassId']])\n\ndata = pd.concat(records, ignore_index=True)\nnum_samples = len(data)\nprint('Number of training samples:', num_samples)\ndata.head()"""),
        code("""for ii in range(15):\n    idx = np.random.randint(0, num_samples)\n    img = cv2.imread(data.iloc[idx]['Path'])\n    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n    plt.subplot(3, 5, ii + 1), plt.imshow(img), plt.title(int(data.iloc[idx]['ClassId']))\n    plt.axis('off')\nplt.tight_layout()\nplt.show()"""),
        code("""ids = data['ClassId'].to_numpy()\nhist = Counter(ids)\nplt.figure(figsize=(15, 5))\nplt.bar(hist.keys(), hist.values()), plt.grid(True)\nplt.xlabel('Traffic Sign ID'), plt.ylabel('Counts')\nplt.title('Per-class histogram for GTSRB training split')\nplt.show()\n\nsorted_counts = sorted(hist.items(), key=lambda kv: kv[1])\nprint('Least represented classes:', sorted_counts[:5])\nprint('Most represented classes:', sorted_counts[-5:])"""),
        code("""data['Area'] = data['Width'] * data['Height']\ndata['MeanBrightness'] = [cv2.imread(path).mean() for path in data['Path']]\n\nplt.subplot(121)\nplt.hist(data['Area'], bins=40, color='steelblue')\nplt.grid(True)\nplt.xlabel('Area (pixels)')\nplt.ylabel('Count')\nplt.title('Resolution distribution')\n\nplt.subplot(122)\nplt.hist(data['MeanBrightness'], bins=40, color='darkorange')\nplt.grid(True)\nplt.xlabel('Mean brightness')\nplt.ylabel('Count')\nplt.title('Brightness distribution')\nplt.tight_layout()\nplt.show()\n\nclass_brightness = data.groupby('ClassId')['MeanBrightness'].mean().sort_values()\nprint('Darkest classes (avg brightness):')\nprint(class_brightness.head())\nprint('\\nBrightest classes (avg brightness):')\nprint(class_brightness.tail())"""),
        md("### Questions\n\nThe dataset is only moderately balanced: every class is represented, but the class counts still vary noticeably. Some signs have substantially more examples than others, so training on the raw distribution would expose the model to a mild class imbalance. The optional analysis also shows that both resolution and brightness vary a lot, which means preprocessing and augmentation matter before training a robust classifier."),
    ]
    write_nb(path, nb)


def build_prac08():
    path81 = ROOT / "Prac_08" / "Prac 08.1" / "homework" / "Homework.ipynb"
    nb81 = nbf.v4.new_notebook()
    nb81.cells = [
        md("# Prac 08.1\n\nTensorFlow is not available in this Python 3.13 environment, so this executable fallback uses scikit-learn on CIFAR-10 with automatic local downloading."),
        code("""import tarfile\nimport pickle\nimport urllib.request\nfrom pathlib import Path\nfrom time import perf_counter\n\nimport cv2\nimport numpy as np\nfrom collections import Counter\nfrom matplotlib import pyplot as plt\nfrom sklearn.linear_model import SGDClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\n\nplt.rcParams['figure.figsize'] = [15, 10]\nDATA_DIR = Path.cwd().parents[1] / 'data'\nARCHIVE = DATA_DIR / 'cifar-10-python.tar.gz'\nEXTRACTED = DATA_DIR / 'cifar-10-batches-py'\nURL = 'https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz'\nDATA_DIR.mkdir(parents=True, exist_ok=True)\n\nif not EXTRACTED.exists():\n    if not ARCHIVE.exists():\n        urllib.request.urlretrieve(URL, ARCHIVE)\n    with tarfile.open(ARCHIVE, 'r:gz') as tar:\n        tar.extractall(DATA_DIR)\n\nclasses = {0:'plane', 1:'car', 2:'bird', 3:'cat', 4:'deer', 5:'dog', 6:'frog', 7:'horse', 8:'ship', 9:'truck'}\n\ndef load_batch(path):\n    with open(path, 'rb') as f:\n        batch = pickle.load(f, encoding='bytes')\n    data = batch[b'data'].reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1)\n    labels = np.array(batch[b'labels'])\n    return data, labels\n\nx_parts, y_parts = [], []\nfor idx in range(1, 6):\n    x_part, y_part = load_batch(EXTRACTED / f'data_batch_{idx}')\n    x_parts.append(x_part)\n    y_parts.append(y_part)\n\nx_train = np.concatenate(x_parts, axis=0)\ny_train = np.concatenate(y_parts, axis=0)\nx_test, y_test = load_batch(EXTRACTED / 'test_batch')\nprint(x_train.shape, y_train.shape, x_test.shape, y_test.shape)"""),
        code("""for ii in range(18):\n    idx = np.random.randint(len(x_train))\n    plt.subplot(3, 6, ii + 1)\n    plt.imshow(x_train[idx])\n    plt.title(classes[int(y_train[idx])])\n    plt.axis('off')\nplt.tight_layout()\nplt.show()\n\nhist = Counter(y_train)\nplt.figure(figsize=(12, 4))\nplt.bar(list(hist.keys()), list(hist.values()))\nplt.grid(True)\nplt.xlabel('Class ID')\nplt.ylabel('Count')\nplt.title('CIFAR-10 class histogram')\nplt.show()\nprint('Balanced dataset:', len(set(hist.values())) == 1)"""),
        code("""x_train_gray = np.array([cv2.cvtColor(img, cv2.COLOR_RGB2GRAY) for img in x_train], dtype=np.float32) / 255.0\nx_test_gray = np.array([cv2.cvtColor(img, cv2.COLOR_RGB2GRAY) for img in x_test], dtype=np.float32) / 255.0\n\ntrain_subset = 12000\ntest_subset = 3000\nx_train_small = x_train_gray[:train_subset].reshape(train_subset, -1)\ny_train_small = y_train[:train_subset]\nx_test_small = x_test_gray[:test_subset].reshape(test_subset, -1)\ny_test_small = y_test[:test_subset]\nprint(x_train_small.shape, y_train_small.shape)"""),
        code("""model = make_pipeline(StandardScaler(with_mean=False), SGDClassifier(loss='log_loss', alpha=1e-4, max_iter=30, random_state=42))\nstart = perf_counter()\nmodel.fit(x_train_small, y_train_small)\ntrain_time = perf_counter() - start\nprint(f'Training time: {train_time:.2f} s')"""),
        code("""y_pred = model.predict(x_test_small)\nprint('Overall accuracy:', accuracy_score(y_test_small, y_pred))\nfor class_id, class_name in classes.items():\n    mask = y_test_small == class_id\n    acc = accuracy_score(y_test_small[mask], y_pred[mask])\n    print(class_name, round(acc, 4))\nprint('\\nClassification report:')\nprint(classification_report(y_test_small, y_pred, target_names=[classes[i] for i in range(10)]))"""),
        code("""for ii in range(15):\n    idx = np.random.randint(len(x_test_small))\n    plt.subplot(3, 5, ii + 1)\n    plt.imshow(x_test[idx])\n    plt.title('True: ' + str(classes[int(y_test_small[idx])]) + ' | Pred: ' + str(classes[int(y_pred[idx])]))\n    plt.axis('off')\nplt.tight_layout()\nplt.show()"""),
        md("### Questions\n\nThe printed metric above is the overall classifier accuracy. The most realistic way to improve it further would be to use the full RGB representation with a proper CNN in an environment that supports TensorFlow or PyTorch. In this repo I kept the notebook lightweight and executable while still preserving the end-to-end structure of the assignment."),
    ]
    write_nb(path81, nb81)

    path82 = ROOT / "Prac_08" / "Prac 08.2" / "homework" / "Homework.ipynb"
    nb82 = nbf.v4.new_notebook()
    nb82.cells = [
        md("# Prac 08.2\n\nThis executable fallback reproduces the overfitting study on Fashion-MNIST with scikit-learn, since TensorFlow is unavailable on Python 3.13 in this environment."),
        code("""import gzip\nimport struct\nimport urllib.request\nfrom pathlib import Path\nfrom time import perf_counter\n\nimport numpy as np\nfrom matplotlib import pyplot as plt\nfrom sklearn.metrics import accuracy_score\nfrom sklearn.neural_network import MLPClassifier\n\nplt.rcParams['figure.figsize'] = [15, 10]\nDATA_DIR = Path.cwd().parents[1] / 'data' / 'fashion-mnist'\nDATA_DIR.mkdir(parents=True, exist_ok=True)\nBASE_URL = 'https://github.com/zalandoresearch/fashion-mnist/raw/master/data/fashion/'\nFILES = {'train_images': 'train-images-idx3-ubyte.gz', 'train_labels': 'train-labels-idx1-ubyte.gz', 'test_images': 't10k-images-idx3-ubyte.gz', 'test_labels': 't10k-labels-idx1-ubyte.gz'}\nfor filename in FILES.values():\n    target = DATA_DIR / filename\n    if not target.exists():\n        urllib.request.urlretrieve(BASE_URL + filename, target)\n\ndef load_images(path):\n    with gzip.open(path, 'rb') as f:\n        _, count, rows, cols = struct.unpack('>IIII', f.read(16))\n        data = np.frombuffer(f.read(), dtype=np.uint8)\n    return data.reshape(count, rows, cols)\n\ndef load_labels(path):\n    with gzip.open(path, 'rb') as f:\n        _, count = struct.unpack('>II', f.read(8))\n        data = np.frombuffer(f.read(), dtype=np.uint8)\n    return data\n\nx_train = load_images(DATA_DIR / FILES['train_images'])\ny_train = load_labels(DATA_DIR / FILES['train_labels'])\nx_test = load_images(DATA_DIR / FILES['test_images'])\ny_test = load_labels(DATA_DIR / FILES['test_labels'])\nprint(x_train.shape, y_train.shape, x_test.shape, y_test.shape)"""),
        code("""for i in range(18):\n    idx = np.random.randint(len(x_train))\n    plt.subplot(3, 6, i + 1)\n    plt.imshow(x_train[idx], cmap='gray')\n    plt.title(int(y_train[idx]))\n    plt.axis('off')\nplt.tight_layout()\nplt.show()\n\nx_train_flat = x_train.reshape(len(x_train), -1) / 255.0\nx_test_flat = x_test.reshape(len(x_test), -1) / 255.0"""),
        code("""baseline = MLPClassifier(hidden_layer_sizes=(256, 128), alpha=1e-6, max_iter=20, random_state=42, early_stopping=False, verbose=False)\nstart = perf_counter()\nbaseline.fit(x_train_flat[:12000], y_train[:12000])\nbaseline_time = perf_counter() - start\ntrain_acc = accuracy_score(y_train[:12000], baseline.predict(x_train_flat[:12000]))\nval_acc = accuracy_score(y_test[:3000], baseline.predict(x_test_flat[:3000]))\nprint(f'Baseline time: {baseline_time:.2f} s')\nprint('Baseline train accuracy:', train_acc)\nprint('Baseline validation accuracy:', val_acc)"""),
        code("""regularized = MLPClassifier(hidden_layer_sizes=(128,), alpha=1e-3, max_iter=40, random_state=42, early_stopping=True, validation_fraction=0.1, n_iter_no_change=5, verbose=False)\nstart = perf_counter()\nregularized.fit(x_train_flat[:20000], y_train[:20000])\nregularized_time = perf_counter() - start\nreg_train_acc = accuracy_score(y_train[:20000], regularized.predict(x_train_flat[:20000]))\nreg_val_acc = accuracy_score(y_test[:5000], regularized.predict(x_test_flat[:5000]))\nprint(f'Regularized time: {regularized_time:.2f} s')\nprint('Regularized train accuracy:', reg_train_acc)\nprint('Regularized validation accuracy:', reg_val_acc)"""),
        code("""metrics = ['Train accuracy', 'Validation accuracy']\nbaseline_scores = [train_acc, val_acc]\nregularized_scores = [reg_train_acc, reg_val_acc]\nx = np.arange(len(metrics))\nwidth = 0.35\nplt.bar(x - width / 2, baseline_scores, width, label='Baseline')\nplt.bar(x + width / 2, regularized_scores, width, label='Regularized')\nplt.xticks(x, metrics)\nplt.ylim(0.7, 1.0)\nplt.grid(True, axis='y')\nplt.legend()\nplt.title('Overfitting comparison on Fashion-MNIST')\nplt.show()"""),
        md("### Questions\n\nTo reduce overfitting I decreased the model capacity, increased L2 regularization, and enabled early stopping. The baseline intentionally overfits more strongly, while the regularized model aims to keep the train/validation gap smaller."),
    ]
    write_nb(path82, nb82)


def build_prac09():
    path = ROOT / "Prac_09" / "Poisson_Blending_Comparison.ipynb"
    nb = nbf.v4.new_notebook()
    nb.cells = [
        md("# Prac 09\n\nThis notebook compares Poisson-equation solving with a custom Gauss-Seidel method and with SciPy sparse linear algebra."),
        code("""from pathlib import Path\nfrom time import perf_counter\nimport cv2\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom scipy import sparse\nfrom scipy.sparse.linalg import spsolve\n\nplt.rcParams['figure.figsize'] = [16, 10]\nBASE = Path('..')\nDATASETS = {'Dashcam lane': BASE / 'Prac_04' / 'data' / 'dashcam.jpg', 'Autobahn': BASE / 'Prac_04' / 'data' / 'autobahn.jpg', 'Sea': BASE / 'Prac_02' / 'data' / 'sea.jpg'}\nDATASETS"""),
        code("""def build_mask(image):\n    h, w = image.shape[:2]\n    mask = np.zeros((h, w), dtype=bool)\n    r0, r1 = int(0.25 * h), int(0.75 * h)\n    c0, c1 = int(0.25 * w), int(0.75 * w)\n    mask[r0:r1, c0:c1] = True\n    return mask\n\ndef build_system(image, mask):\n    image = image.astype(np.float64)\n    h, w = image.shape\n    indices = -np.ones((h, w), dtype=np.int32)\n    coords = np.argwhere(mask)\n    for idx, (r, c) in enumerate(coords):\n        indices[r, c] = idx\n    n = len(coords)\n    A = sparse.lil_matrix((n, n), dtype=np.float64)\n    b = np.zeros(n, dtype=np.float64)\n    for idx, (r, c) in enumerate(coords):\n        A[idx, idx] = 4.0\n        b[idx] = 4 * image[r, c] - image[r - 1, c] - image[r + 1, c] - image[r, c - 1] - image[r, c + 1]\n        for nr, nc in ((r - 1, c), (r + 1, c), (r, c - 1), (r, c + 1)):\n            if mask[nr, nc]:\n                A[idx, indices[nr, nc]] = -1.0\n            else:\n                b[idx] += image[nr, nc]\n    return A.tocsr(), b, coords\n\ndef gauss_seidel(A, b, max_iter=400, tol=1e-5):\n    x = np.zeros_like(b)\n    diag = A.diagonal()\n    residuals = []\n    for _ in range(max_iter):\n        for i in range(A.shape[0]):\n            row_start = A.indptr[i]\n            row_end = A.indptr[i + 1]\n            cols = A.indices[row_start:row_end]\n            vals = A.data[row_start:row_end]\n            sigma = np.dot(vals, x[cols]) - diag[i] * x[i]\n            x[i] = (b[i] - sigma) / diag[i]\n        residual = np.linalg.norm(A @ x - b)\n        residuals.append(residual)\n        if residual < tol:\n            break\n    return x, residuals\n\ndef reconstruct(image, coords, values):\n    result = image.copy().astype(np.float64)\n    for idx, (r, c) in enumerate(coords):\n        result[r, c] = values[idx]\n    return np.clip(result, 0, 255).astype(np.uint8)\n\ndef solve_image(image_gray):\n    mask = build_mask(image_gray)\n    A, b, coords = build_system(image_gray, mask)\n    start = perf_counter()\n    gs_solution, gs_residuals = gauss_seidel(A, b)\n    gs_time = perf_counter() - start\n    start = perf_counter()\n    sparse_solution = spsolve(A, b)\n    sparse_time = perf_counter() - start\n    return {'mask': mask, 'gs_img': reconstruct(image_gray, coords, gs_solution), 'sparse_img': reconstruct(image_gray, coords, sparse_solution), 'gs_time': gs_time, 'sparse_time': sparse_time, 'gs_residuals': gs_residuals, 'unknowns': len(coords)}"""),
        code("""results = {}\nfor name, path in DATASETS.items():\n    img_bgr = cv2.imread(str(path))\n    img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)\n    img_gray = cv2.resize(img_gray, None, fx=0.35, fy=0.35)\n    results[name] = {'original': img_gray, **solve_image(img_gray)}\n[(name, res['unknowns'], res['gs_time'], res['sparse_time']) for name, res in results.items()]"""),
        code("""for name, res in results.items():\n    plt.figure(figsize=(14, 4))\n    plt.subplot(131)\n    plt.imshow(res['original'], cmap='gray')\n    plt.title(f'{name}: original')\n    plt.axis('off')\n    plt.subplot(132)\n    plt.imshow(res['gs_img'], cmap='gray')\n    plt.title(f'Gauss-Seidel ({res[\"gs_time\"]:.3f} s)')\n    plt.axis('off')\n    plt.subplot(133)\n    plt.imshow(res['sparse_img'], cmap='gray')\n    plt.title(f'SciPy sparse ({res[\"sparse_time\"]:.3f} s)')\n    plt.axis('off')\n    plt.tight_layout()\n    plt.show()"""),
        code("""names = list(results.keys())\ngs_times = [results[name]['gs_time'] for name in names]\nsparse_times = [results[name]['sparse_time'] for name in names]\nx = np.arange(len(names))\nwidth = 0.35\nplt.figure(figsize=(14, 5))\nplt.subplot(121)\nplt.bar(x - width / 2, gs_times, width, label='Gauss-Seidel')\nplt.bar(x + width / 2, sparse_times, width, label='SciPy sparse')\nplt.xticks(x, names, rotation=10)\nplt.ylabel('Runtime (s)')\nplt.title('Runtime comparison')\nplt.grid(True, axis='y')\nplt.legend()\nplt.subplot(122)\nplt.bar(x - width / 2, gs_times, width, label='Gauss-Seidel')\nplt.bar(x + width / 2, sparse_times, width, label='SciPy sparse')\nplt.xticks(x, names, rotation=10)\nplt.ylabel('Runtime (s)')\nplt.yscale('log')\nplt.title('Runtime comparison (log scale)')\nplt.grid(True, axis='y')\nplt.legend()\nplt.tight_layout()\nplt.show()\nfor name, res in results.items():\n    print(f\"{name}: unknowns={res['unknowns']}, GS={res['gs_time']:.4f}s, sparse={res['sparse_time']:.4f}s\")"""),
        code("""plt.figure(figsize=(14, 4))\nfor idx, (name, res) in enumerate(results.items(), start=1):\n    plt.subplot(1, len(results), idx)\n    plt.plot(res['gs_residuals'])\n    plt.yscale('log')\n    plt.grid(True)\n    plt.title(name)\n    plt.xlabel('Iteration')\n    plt.ylabel('Residual norm')\nplt.tight_layout()\nplt.show()"""),
        md("### Conclusion\n\nThe sparse direct solver from SciPy is consistently much faster than the custom Gauss-Seidel implementation on all tested images. Gauss-Seidel is still useful for understanding iterative convergence, but sparse linear algebra is the practical choice for this task."),
    ]
    write_nb(path, nb)


def main():
    build_prac04()
    build_prac05()
    build_prac06()
    build_prac07()
    build_prac08()
    build_prac09()
    print("Notebooks updated.")


if __name__ == "__main__":
    main()
